# -*- coding: utf-8 -*-
"""
中英双语文案模板配置
用于统一管理邮件、TG群、Lark等各种发送渠道的双语文案
"""

from datetime import datetime
from typing import Dict, Any

class BilingualTemplates:
    """双语文案模板类"""
    
    @staticmethod
    def get_email_internal_confirmation_template() -> Dict[str, str]:
        """获取邮件内部确认模板"""
        return {
            'subject': '月度账单内部确认 Monthly Bill Internal Confirmation - {period}',
            'header_title': '[INFO] 月度账单内部确认<br>Monthly Bill Internal Confirmation',
            'period_label': '账单月份 Billing Period',
            'generation_time_label': '生成时间 Generation Time',
            'summary_title': '[INFO] 账单汇总 Bill Summary',
            'merchant_count_label': '商户数量 Merchant Count',
            'total_amount_label': '总应付金额 Total Payable Amount',
            'merchant_details_title': '[EMOJI] 商户明细 Merchant Details',
            'merchant_item_template': '<strong>{merchant_name}</strong> - ${amount:,.2f} USD ({sub_merchant_count} 个子账户 sub-accounts)',
            'confirm_button': '[SUCCESS] 确认发送账单<br>Confirm Send Bills',
            'reject_button': '[ERROR] 拒绝发送<br>Reject Sending',
            'footer_company': 'Gaming Panda | 财务系统自动生成<br>Gaming Panda | Auto-generated by Finance System',
            'footer_contact': '若对账单存疑，可联系客服<br>If you have any questions about the bill, please contact customer service.'
        }
    
    @staticmethod
    def get_email_customer_bill_template() -> Dict[str, str]:
        """获取邮件客户账单模板"""
        return {
            'subject': '月度账单 Monthly Bill - {merchant_name} - {period}',
            'header_title': '月度账单<br>Monthly Bill',
            'greeting': '尊敬的 {merchant_name} 客户，<br>Dear {merchant_name},',
            'intro': '您好！以下是您的月度账单详情：<br>Hello! Here are the details of your monthly bill:',
            'bill_info_title': '[INFO] 账单信息 Bill Information',
            'merchant_name_label': '商户名称 Merchant Name',
            'bill_period_label': '账单月份 Billing Period',
            'sub_merchant_count_label': '子商户数 Sub-merchant Count',
            'payable_amount_label': '应付金额 Payable Amount',
            'generation_date_label': '生成日期 Generation Date',
            'attachment_notice': '请查看附件中的详细账单PDF文件。<br>Please check the detailed bill PDF file in the attachment.',
            'contact_notice': '如有任何疑问，请及时联系我们。<br>If you have any questions, please contact us in time.',
            'footer_contact': '若对账单存疑，可联系客服<br>If you have any questions about the bill, please contact customer service.',
            'footer_payment': 'Gaming Panda | 汇款链接 Payment Link: TMuwXuWKd4az3KuYHZgssLj3WqvVSHyKfr'
        }
    
    @staticmethod
    def get_telegram_bill_notification_template() -> Dict[str, str]:
        """获取TG账单通知模板"""
        return {
            'title': '[EMOJI] <b>月度账单通知 Monthly Bill Notification</b>',
            'merchant_info_title': '[INFO] <b>商户信息 Merchant Information</b>',
            'merchant_name_label': '• 商户名称 Merchant Name: {merchant_name}',
            'sub_merchant_count_label': '• 子商户数 Sub-merchants: {sub_merchant_count}',
            'payable_amount_label': '• 应付金额 Payable Amount: ${total_amount:,.2f} USD',
            'bill_details_title': '[INFO] <b>账单详情 Bill Details</b>',
            'bill_period_label': '• 账单月份 Billing Period: {period}',
            'generation_time_label': '• 生成时间 Generation Time: {generation_time}',
            'payment_info_title': '[EMOJI] <b>汇款信息 Payment Information</b>',
            'payment_link': 'Gaming Panda | 汇款链接 Payment Link: TMuwXuWKd4az3KuYHZgssLj3WqvVSHyKfr',
            'contact_notice': '[EMOJI] 若对账单存疑，可联系客服<br>If you have any questions about the bill, please contact customer service.'
        }
    
    @staticmethod
    def get_telegram_bill_send_template() -> Dict[str, str]:
        """获取TG账单发送模板（confirm_handler中使用）"""
        return {
            'title': '📄 账单发送 Bill Delivery',
            'merchant_label': '商户 Merchant: {merchant_id}',
            'period_label': '期间 Period: {period}',
            'generation_time_label': '生成时间 Generation Time: {generation_time}',
            'notice': '请查收您的账单文件。\nPlease check your bill file.',
            'caption_template': '[EMOJI] {merchant_name} - 月度账单PDF\nMonthly Bill PDF'
        }
    
    @staticmethod
    def get_lark_confirmation_template() -> Dict[str, str]:
        """获取Lark确认消息模板"""
        return {
            'title': '账单确认 Bill Confirmation - {period}',
            'file_label': '文件 File: {zip_file}',
            'period_label': '期间 Period: {period}',
            'total_amount_label': '总金额 Total Amount: {total_amount:,.2f} USDT',
            'merchant_count_label': '商户数量 Merchant Count: {merchant_count}个',
            'merchant_details_title': '商户明细 Merchant Details:',
            'merchant_item_template': '• {merchant_name}: ${amount:,.2f} USD ({sub_merchant_count} 个子账户 sub-accounts)',
            'more_merchants_notice': '... 还有 {remaining_count} 个商户未显示<br>... {remaining_count} more merchants not displayed',
            'full_list_notice': '完整商户列表请查看ZIP文件内容<br>Please check ZIP file for complete merchant list',
            'confirmation_notice': '请确认账单信息无误后，点击下方按钮发送给客户。<br>Please confirm the bill information is correct, then click the button below to send to customers.',
            'generation_time_label': '生成时间 Generation Time: {generation_time}'
        }
    
    @staticmethod
    def get_send_results_template() -> Dict[str, str]:
        """获取发送结果汇总模板"""
        return {
            'title': '账单发送结果汇总 Bill Sending Results Summary - {period}',
            'statistics_title': '**发送统计 Sending Statistics**:',
            'total_merchants_label': '- 总商户数 Total Merchants: {total_count}',
            'success_count_label': '- 发送成功 Successful: {success_count}',
            'failed_count_label': '- 发送失败 Failed: {failed_count}',
            'detailed_results_title': '**详细结果 Detailed Results**:',
            'success_item_template': '**{merchant_name}**: ✅ {channel}: {target} - 发送成功 Sent successfully',
            'failed_item_template': '**{merchant_name}**: ❌ {channel}: {target} - {reason}'
        }
    
    @staticmethod
    def format_email_internal_confirmation(merchant_data: Dict[str, Any], confirmation_url: str) -> str:
        """格式化邮件内部确认内容"""
        template = BilingualTemplates.get_email_internal_confirmation_template()
        merchant_count = len(merchant_data)
        total_amount = sum(data.get('total_amount', 0) for data in merchant_data.values())
        period = datetime.now().strftime('%Y年%m月')
        
        # 构建商户明细
        merchant_items = ""
        for merchant_name, data in merchant_data.items():
            amount = data.get('total_amount', 0)
            sub_merchant_count = data.get('sub_merchant_count', 0)
            merchant_items += f"""
                <div class="merchant-item">
                    {template['merchant_item_template'].format(
                        merchant_name=merchant_name,
                        amount=amount,
                        sub_merchant_count=sub_merchant_count
                    )}
                </div>
            """
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                .header {{ background-color: #f8f9fa; padding: 20px; border-radius: 5px; text-align: center; }}
                .summary {{ background-color: #e9ecef; padding: 15px; margin: 20px 0; border-radius: 5px; }}
                .merchant-list {{ margin: 20px 0; }}
                .merchant-item {{ padding: 10px; border-bottom: 1px solid #dee2e6; }}
                .confirm-button {{ 
                    background-color: #28a745; color: white; padding: 12px 24px; 
                    text-decoration: none; border-radius: 5px; 
                    display: inline-block; margin: 20px 10px;
                }}
                .reject-button {{ 
                    background-color: #dc3545; color: white; padding: 12px 24px; 
                    text-decoration: none; border-radius: 5px; 
                    display: inline-block; margin: 20px 10px;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h2>{template['header_title']}</h2>
                <p>{template['period_label']}: {period}</p>
                <p>{template['generation_time_label']}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>
            
            <div class="summary">
                <h3>{template['summary_title']}</h3>
                <p><strong>{template['merchant_count_label']}:</strong> {merchant_count} 个</p>
                <p><strong>{template['total_amount_label']}:</strong> ${total_amount:,.2f} USD</p>
            </div>
            
            <div class="merchant-list">
                <h3>{template['merchant_details_title']}</h3>
                {merchant_items}
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
                <a href="{confirmation_url}?action=confirm" class="confirm-button">{template['confirm_button']}</a>
                <a href="{confirmation_url}?action=reject" class="reject-button">{template['reject_button']}</a>
            </div>
            
            <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6; color: #6c757d;">
                <p><small>{template['footer_company']}</small></p>
                <p><small>{template['footer_contact']}</small></p>
            </div>
        </body>
        </html>
        """
        
        return html_content
    
    @staticmethod
    def format_email_customer_bill(merchant_name: str, merchant_data: Dict[str, Any]) -> str:
        """格式化邮件客户账单内容"""
        template = BilingualTemplates.get_email_customer_bill_template()
        total_amount = merchant_data.get('total_amount', 0)
        sub_merchant_count = merchant_data.get('sub_merchant_count', 0)
        period = datetime.now().strftime('%Y年%m月')
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                .header {{ background-color: #f8f9fa; padding: 20px; border-radius: 5px; text-align: center; }}
                .content {{ margin: 20px 0; }}
                .summary {{ background-color: #e9ecef; padding: 15px; margin: 20px 0; border-radius: 5px; }}
                .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6; color: #6c757d; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h2>{template['header_title']}</h2>
                <p>www.gaming-panda.com</p>
            </div>
            
            <div class="content">
                <h3>{template['greeting'].format(merchant_name=merchant_name)}</h3>
                <p>{template['intro']}</p>
                
                <div class="summary">
                    <h4>{template['bill_info_title']}</h4>
                    <p><strong>{template['merchant_name_label']}:</strong> {merchant_name}</p>
                    <p><strong>{template['bill_period_label']}:</strong> {period}</p>
                    <p><strong>{template['sub_merchant_count_label']}:</strong> {sub_merchant_count}</p>
                    <p><strong>{template['payable_amount_label']}:</strong> ${total_amount:,.2f} USD</p>
                    <p><strong>{template['generation_date_label']}:</strong> {datetime.now().strftime('%Y-%m-%d')}</p>
                </div>
                
                <p>{template['attachment_notice']}</p>
                <p>{template['contact_notice']}</p>
            </div>
            
            <div class="footer">
                <p>{template['footer_contact']}</p>
                <p><strong>{template['footer_payment']}</strong></p>
            </div>
        </body>
        </html>
        """
        
        return html_content
    
    @staticmethod
    def format_telegram_bill_notification(merchant_name: str, merchant_data: Dict[str, Any]) -> str:
        """格式化TG账单通知内容"""
        template = BilingualTemplates.get_telegram_bill_notification_template()
        total_amount = merchant_data.get('total_amount', 0)
        sub_merchant_count = merchant_data.get('sub_merchant_count', 0)
        period = datetime.now().strftime('%Y年%m月')
        generation_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        message = f"""
{template['title']}

{template['merchant_info_title']}
{template['merchant_name_label'].format(merchant_name=merchant_name)}
{template['sub_merchant_count_label'].format(sub_merchant_count=sub_merchant_count)}
{template['payable_amount_label'].format(total_amount=total_amount)}

{template['bill_details_title']}
{template['bill_period_label'].format(period=period)}
{template['generation_time_label'].format(generation_time=generation_time)}

{template['payment_info_title']}
{template['payment_link']}

{template['contact_notice']}
        """
        
        return message.strip()
    
    @staticmethod
    def format_telegram_bill_send(merchant_id: str, period: str) -> str:
        """格式化TG账单发送内容（confirm_handler中使用）"""
        template = BilingualTemplates.get_telegram_bill_send_template()
        generation_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        message = f"""
{template['title']}

{template['merchant_label'].format(merchant_id=merchant_id)}
{template['period_label'].format(period=period)}
{template['generation_time_label'].format(generation_time=generation_time)}

{template['notice']}
        """
        
        return message.strip()
    
    @staticmethod
    def format_lark_confirmation(zip_file: str, summary_data: Dict[str, Any]) -> str:
        """格式化Lark确认消息内容"""
        template = BilingualTemplates.get_lark_confirmation_template()
        period = datetime.now().strftime('%Y年%m月')
        generation_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        merchant_count = summary_data.get('total_count', 0)
        total_amount = summary_data.get('total_amount', 0)
        
        message = f"""{template['title'].format(period=period)}

{template['file_label'].format(zip_file=zip_file)}
{template['period_label'].format(period=period)}
{template['total_amount_label'].format(total_amount=total_amount)}
{template['merchant_count_label'].format(merchant_count=merchant_count)}

{template['merchant_details_title']}"""
        
        # 添加商户明细（限制显示数量）
        max_display = 10
        merchant_data = summary_data.get('merchants', {})
        displayed_count = 0
        
        for merchant_name, data in merchant_data.items():
            if displayed_count >= max_display:
                break
            amount = data.get('total_amount', 0)
            sub_merchant_count = data.get('sub_merchant_count', 0)
            message += f"\n{template['merchant_item_template'].format(
                merchant_name=merchant_name,
                amount=amount,
                sub_merchant_count=sub_merchant_count
            )}"
            displayed_count += 1
        
        # 如果还有更多商户未显示
        if merchant_count > max_display:
            remaining_count = merchant_count - max_display
            message += f"\n{template['more_merchants_notice'].format(remaining_count=remaining_count)}"
            message += f"\n{template['full_list_notice']}"
        
        message += f"""

{template['confirmation_notice']}

{template['generation_time_label'].format(generation_time=generation_time)}"""
        
        return message